server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gyeol?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dydwls0716

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  profiles:
    include: oauth

minio:
  url: http://localhost:9000
  access-key: root
  secret-key: dydwls0716
  bucket: gyeol

jwt:
  secret: "my-super-long-secret-key-that-is-at-least-32-characters"

