server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://gyeoldb.cx08oc6c8i7a.ap-northeast-2.rds.amazonaws.com:3306/gyeol?serverTimezone=Asia/Seoul&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ec2user
    password: dydwls0716

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  profiles:
    include: oauth


jwt:
  secret: "my-super-long-secret-key-that-is-at-least-32-characters"

